# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 223868bff8bbf5ac90f4aaf54ad53e703868b07e5d9d0146a9499e6c4d649f3826e36d98ae848b1ad3cf1b934735b316274a04c398a8d0d7cdb4682e5809ef1d

test:
  secret_key_base: 13a2520f5ae1d1d0bd870d2c1cdf2fbf0f41c418e55aef57f350e5753c27df7849c78bdfd109091d27ae481e6037a9bf2d2208a18248186c4405abc40624da85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
